UPDATE CHALLENGE_REPORTS_STATUS_CODE
SET CHALLENGE_REPORTS_STATUS_CODE = 'NT_STARTED',
    LABEL = 'Not Started',
    DESCRIPTION = 'Not Started Stage'
where CHALLENGE_REPORTS_STATUS_CODE = 'PRE_EMAIL';

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2025-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2026-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2027-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2028-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2029-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2030-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2031-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2032-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2033-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2034-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2035-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2036-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2037-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2038-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2039-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2040-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2041-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2042-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2043-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);
INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)

VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2044-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_SESSION (CHALLENGE_REPORTS_SESSION_ID, CHALLENGE_REPORTS_PERIOD_ID, CHALLENGE_REPORTS_STATUS_CODE,
                                       CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), (SELECT CHALLENGE_REPORTS_PERIOD_ID FROM CHALLENGE_REPORTS_PERIOD WHERE to_date('2045-08-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS') BETWEEN ACTIVE_FROM_DATE AND ACTIVE_TO_DATE),
        'NT_STARTED',
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);
