CREATE TABLE CHALLENGE_REPORTS_STATUS_CODE
(
    CHALLENGE_REPORTS_STATUS_CODE VARCHAR(10)                         NOT NULL,
    LABEL                         VARCHAR(50)                         NOT NULL,
    DESCRIPTION                   VARCHAR(255)                        NOT NULL,
    DISPLAY_ORDER                 NUMERIC   DEFAULT 1                 NOT NULL,
    EFFECTIVE_DATE                TIMESTAMP                           NOT NULL,
    EXPIRY_DATE                   TIMESTAMP                           NOT NULL,
    LANGUAGE                      VARCHAR(1),
    CREATE_USER                   VARCHAR(100)                         NOT NULL,
    CREATE_DATE                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_USER                   VARCHAR(100)                         NOT NULL,
    UPDATE_DATE                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHALLENGE_REPORTS_STATUS_CODE_PK PRIMARY KEY (CHALLENGE_REPORTS_STATUS_CODE)
);

INSERT INTO CHALLENGE_REPORTS_STATUS_CODE (CHALLENGE_REPORTS_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE,
                              CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('PRELIM', 'Preliminary Stage', 'Preliminary Stage', 10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_STATUS_CODE (CHALLENGE_REPORTS_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE, EXPIRY_DATE,
                              CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('FINALIZED', 'Finalized Stage', 'Finalized Stage', 20,
        to_date('2021-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

