CREATE TABLE CHALLENGE_REPORTS_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT CHALLENGE_REPORTS_SHEDLOCK_PK PRIMARY KEY (NAME)
);

alter table CHALLENGE_REPORTS_SAGA_EVENT_STATES DROP CONSTRAINT CHALLENGE_REPORTS_SAGA_EVENT_STATES_SAGA_ID_FK;
ALTER TABLE CHALLENGE_REPORTS_SAGA_EVENT_STATES ADD CONSTRAINT CHALLENGE_REPORTS_SAGA_EVENT_STATES_SAGA_ID_FK FOREIGN KEY (SAGA_ID) REFERENCES CHALLENGE_REPORTS_SAGA(SAGA_ID) on delete cascade;
