UPDATE CHALLENGE_REPORTS_STATUS_CODE
SET
    LABEL = 'Not Yet Available',
    UPDATE_USER = 'CHALLENGE_REPORTS-API',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE
    CHALLENGE_REPORTS_STATUS_CODE = 'NT_STARTED';

UPDATE CHALLENGE_REPORTS_STATUS_CODE
SET
    LABEL = 'Preliminary',
    UPDATE_USER = 'CHALLENGE_REPORTS-API',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE
    CHALLENGE_REPORTS_STATUS_CODE = 'PRELIM';

UPDATE CHALLENGE_REPORTS_STATUS_CODE
SET
    LABEL = 'Final',
    UPDATE_USER = 'CHALLENGE_REPORTS-API',
    UPDATE_DATE = CURRENT_TIMESTAMP
WHERE
    CHALLENGE_REPORTS_STATUS_CODE = 'FINALIZED';
