ALTER TABLE CHALLENGE_REPORTS_POSTED_STUDENT
    DROP COLUMN COURSE_CODE;

ALTER TABLE CHALLENGE_REPORTS_POSTED_STUDENT
    DROP COLUMN COURSE_LEVEL;

ALTER TABLE CHALLENGE_REPORTS_POSTED_STUDENT
    ADD COURSE_CODE_AND_LEVEL VARCHAR2(10);
