INSERT INTO CHALLENGE_REPORTS_STATUS_CODE (CHALLENGE_REPORTS_STATUS_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER,
                                           EFFECTIVE_DATE, EXPIRY_DATE,
                                           CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('PRE_EMAIL', 'Preliminary Email Stage', 'Preliminary Email Stage', 10,
        to_date('2019-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        to_date('2099-12-31 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2025', to_date('2025-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2026-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2026', to_date('2026-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2027-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2027', to_date('2027-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2028-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2028', to_date('2028-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2029-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2029', to_date('2029-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2030-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);


INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2030', to_date('2030-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2031-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2031', to_date('2031-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2032-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2032', to_date('2032-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2033-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2033', to_date('2033-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2034-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2034', to_date('2034-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2035-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2035', to_date('2035-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2036-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2036', to_date('2036-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2037-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2037', to_date('2037-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2038-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2038', to_date('2038-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2039-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2039', to_date('2039-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2040-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2040', to_date('2040-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2041-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2041', to_date('2041-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2042-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2042', to_date('2042-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2043-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2043', to_date('2043-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2044-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2044', to_date('2044-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2045-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);

INSERT INTO CHALLENGE_REPORTS_PERIOD (CHALLENGE_REPORTS_PERIOD_ID, SCHOOL_YEAR, ACTIVE_FROM_DATE, ACTIVE_TO_DATE,
                                      CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES (SYS_GUID(), '2045', to_date('2045-07-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), to_date('2046-06-31 11:59:59', 'YYYY-MM-DD HH24:MI:SS'),
        'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP, 'CHALLENGE_REPORTS-API', CURRENT_TIMESTAMP);
