package ca.bc.gov.educ.challenge.reports.api.constants.v1;

public enum EventType {
    INITIATED,
    GET_STUDENTS,
    MARK_SAGA_COMPLETE,
    SEND_OUT_PRELIMINARY_EMAIL,
    SEND_OUT_PRELIMINARY_EMAIL_STUD_CERT,
    FETCH_AND_STORE_STUDENTS,
    SEND_OUT_FINAL_EMAIL,
    SEND_OUT_FINAL_EMAIL_STUD_CERT,
    SEND_OUT_INDY_TEAM_EMAIL,
    SEND_OUT_PUBLIC_TEAM_EMAIL,
    UPDATE_SESSION_STATUS
}
